theme: jekyll-theme-cayman
title: Manos Nikolaidis
description: Software Engineer
author: Manos Nikolaidis
twitter:
  username: shadowmanos
social:
  name: Manos Nikolaidis
  links:
    - https://www.linkedin.com/in/manosnikolaidis
    - https://stackoverflow.com/users/1413133/manos-nikolaidis
    - https://twitter.com/shadowmanos
    - https://www.codewars.com/users/shadowmanos
show_downloads: true
google_analytics: UA-100116726-1
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
